spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: service-product
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
        - id: service-user
          uri: http://localhost:8082
          predicates:
            - Path=/product/**
